---
title: "| Data Science With an Eye Towards Sustainability    \n| P5: Narrowing Your Project Topic\n"
author: "Becca, Camille, Sally, Noah, Sherry"
output:
  bookdown::html_document2:
    split_by: none
    toc: no

---


Each group should hand in one html document for the following exercises. Throughout the exercises, keep in mind that your research topics, questions, and data might evolve throughout the course of the project. This checkpoint is simply a first step in narrowing these down.

\

# Names & Workflow

List all group members. Discuss a plan for completing this assignment. How will you put together your shared Rmd? How will you divide the work? When will you meet to work on the assignment? Write this down in your Rmd.

- Try to get most things done in class, and weekly meeting some time during Wednesday afternoon (probably 3 or 4 pm) to check in and have a little bit of co-working time.
- If asynchronous work needs to be done, the work wpuld be assigned to members during in-person meetings


Also, write down your GitHub repository.
- olincollege/mbta-data

\

# Topic & Research Questions

Following on the conversations you've already had in the preliminary brainstorming exercises, identify a common research topic of interest.

- Buses, its ridership, and its use of fuel, its schedule/delays


Specify two to three potential research questions that (1) are related to the topic above; and (2) you can (at least partially) answer using data.

- What factors affect mbta light rail ridership (COVID lockdown, day of the week, time of day, etc)?
- How to quantify the environmental and social sustainability of the light rail (carbon emission per person)?

\

# Connections to Sustainability

How are your research questions connected to sustainability? What are your personal learning goals related to sustainability for this project? You may wish to refer back to the [UN Sustainable Development Goals](https://sdgs.un.org/goals), the [Inner Development Goals](https://innerdevelopmentgoals.org/), and the [Engineering for One Planet](https://engineeringforoneplanet.org/wp-content/uploads/EOP_Framework_2023.pdf?), [Six Pillars of Climate Justice](https://centerclimatejustice.universityofcalifornia.edu/what-is-climate-justice/), and [Just Transition Principles](https://climatejusticealliance.org/just-transition/) frameworks. As a team, what sustainability background, analysis, and  storytellling do you want to include in the scope of your project and in your final artifacts?

- Looking at the MBTA schedule and emissions tie into SDG 11 and its target to provide accessible and sustainable transport systems for all.
- Personally, this project would provide us with insights about the issues and benefits surrounding public transport so we could better advocate for it.

\

# Data

Identify the data sets you will use to explore the research questions above. These data sets may already be in csv form, you may acquire them (e.g., scraped with rvest, via public API, or from an SQL database), or you may plan on collecting some extra data. For each data set, summarize the following:


- data source: 
- data description - what's being measured?
- data limitations (eg: are the data recent? do they contain all variables you might want?)
- data dimensions - how much data do you have?
- how might the data be joined with other data you have?

\

# Research Question 1

Restate research question 1. Construct 3-4 relevant visualizations that provide insight on / help answer this question and piece these together to tell a short story. For each visualization, 1-2 sentences will suffice.

\

# Research Question 2 (and possibly 3)

Repeat the previous exercise for your second and possibly third research questions.

\

# Next Steps

Identify next steps in your analysis. Do you need additional data? Do you need to do more cleaning or wrangling? How might you narrow your research questions/hypotheses? What additional visualizations would be helpful? 

\

# Contributions

Summarize each group member's specific contributions to this checkpoint assignment.

